import { buildFederatedSchema, printSchema } from '@apollo/federation';
import { Injectable } from '@nestjs/common';
import { ResolversExplorerService } from '@nestjs/graphql/dist/services/resolvers-explorer.service';
import { ScalarsExplorerService } from '@nestjs/graphql/dist/services/scalars-explorer.service';
import { extend } from '@nestjs/graphql/dist/utils/extend.util';
import { removeTempField } from '@nestjs/graphql/dist/utils/remove-temp.util';
import { gql } from 'apollo-server-express';
import { GraphQLSchema } from 'graphql';
import { GraphQLSchemaBuilder } from './graphql-schema-builder';
import { DistributedModuleOptions } from './interfaces/distributed-options.interface';
import { ReferencesExplorerService } from './services';
import { addResolversToSchema } from 'apollo-graphql';

@Injectable()
export class GraphqlDistributedFactory {
  constructor(
    private readonly resolversExplorerService: ResolversExplorerService,
    private readonly scalarsExplorerService: ScalarsExplorerService,
    private readonly referencesExplorerService: ReferencesExplorerService,
    private readonly gqlSchemaBuilder: GraphQLSchemaBuilder,
  ) {}

  // @ts-ignore
  public async mergeOptions(options: DistributedModuleOptions = {}): Promise<DistributedModuleOptions> {
    const resolvers = this.extendResolvers([
      this.resolversExplorerService.explore(),
      this.scalarsExplorerService.explore(),
      this.referencesExplorerService.explore(),
    ]);

    if (options.autoSchemaFile) {

      const autoGeneratedSchema: GraphQLSchema = await this.gqlSchemaBuilder.build(
        options.autoSchemaFile,
        options.buildSchemaOptions,
        this.resolversExplorerService.getAllCtors(),
      );

      removeTempField(autoGeneratedSchema);

      const federatedSchemaGen = buildFederatedSchema({
        typeDefs: gql(printSchema(autoGeneratedSchema)),
        resolvers,
      });

      if (options.referenceResolvers) {
        addResolversToSchema(federatedSchemaGen, options.referenceResolvers);
      }

      return {
        ...options,
        typeDefs: undefined,
        schema: federatedSchemaGen,
      };
    }

    const federatedSchema = buildFederatedSchema([
      {
        typeDefs: gql`${options.typeDefs}`,
        resolvers,
      },
    ]);

    removeTempField(federatedSchema);
    return {
      ...options,
      typeDefs: undefined,
      schema: federatedSchema,
    };
  }

  private extendResolvers(resolvers: any[]) {
    // @ts-ignore
    return resolvers.reduce((prev, curr) => extend(prev, curr), {});
  }
}
